### ISSUE TITLE
Week 4 work done

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#1]
@pawaitemadisoncollege hopefully the @ still pings you, not sure if I need to add you to the project or how that works. Got all the stuff up and running using option 2.

I learned a lot about using hibernate, and actually fully creating the test files (since last week the test files were made for us). Also learned a little bit about database view after messing around with it a bit.

One challenge I had was when I was searching for one user by username, I wanted to only get a single result back. I saw the getSingleResult, and thought that was the right method. The problem came when I was testing a deleted user, as that method caused an error instead of returning null. I went into the documentation and found that I should be using getUnique, as that returns null if no results are returned. I also left out the commit part for updating a user, which caused those tests to fail. The demo vids and hibernate examples together were a huge help in figuring things out.

In terms of stuff not from the course website that I used, here's the documentation I looked through to find the getUnique method [jdoc](https://docs.jboss.org/hibernate/orm/5.4/javadocs/). I also was able to avoid db issues thanks to that heads up from Caleb about the config files.

Overall this weeks work went by pretty smooth, assuming no problems I'll keep working on that Enumeration presentation for Tuesday

**Comment by pawaitemadisoncollege** [comment]
Thanks for sharing what you learned about getUnique versus getSingleResult @jholmquest  - I've generally kept my hibernate daos relatively simple (you'll see my generic Dao in another week or so), so haven't used those methods (at least not in any recent history that I remember)! It's good to see that you implemented hibernate in your project already. This will set you up well!

The Dao and unit tests looks very good.   Verifying the entities are saved/updated/inserted correctly could be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/jholmquest/IndieProject/blob/28c544db28b313b06fef03cd373dab1b4a8c0e92/src/test/java/bugnet/persistence/UserDaoTest.java#L51

Looking forward to our first prof dev presentation and thanks for the reminder about it- I need to update our agenda for tomorrow :)

**Comment by jholmquest** [comment]
that does look a lot more convenient than manually comparing, I'll be sure to use that
