### ISSUE TITLE
Week 5 work completed

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#2]
@pawaitemadisoncollege completed my week 5 work, updated to use an overwritten equals method like you mentioned for testing.

My main takeaway from this week was that one to many relationships aren't too bad but you have to remember to update both sides. I also learned the importance of LocalDate vs Date, as once I started testing more thoroughly I discovered there was an issue related to that in one of my classes.

My biggest challenge was this issue when testing adding both a user and a specimen at the same time. I was getting an error that mentioned modifying multiple records at once. I kept going over the differences between my code and the demo for a while and realized it was because I was manually setting ids in my constructor. Once I got rid of that and auto generated them the error went away.

For out of class resources used I went [here](https://www.w3schools.com/sql/sql_dates.asp) to figure out the proper format for my sql script to generate the test database. I also read [this](https://www.overops.com/blog/5-common-hibernate-exceptions-and-how-to-fix-them/) article a bit when I was dealing with that annoying exception, it was #2 the OptimisticLockException.

I forgot to make a new branch but luckily I didn't break anything, will be sure to do so this next week (the branch part not the break everything part).

**Comment by pawaitemadisoncollege** [comment]
Great job implementing the one-to-many in your indie project. You are really rolling right along; nice work keeping your time log up-to-date too! i

- [ ] When implementing in your indie project, think about testing the delete scenarios in one-to-many relationships more fully. For example, if a specimen is deleted, what should happen to the user? What if a user is deleted? Write tests to make sure whatever should happen, does happen.
- [ ] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly.
- [ ] Hiberate has some nice annotations so that you don't have to worry about how to populate current time values: 
[Create Timestamp](https://docs.jboss.org/hibernate/stable/orm/userguide/html_single/Hibernate_User_Guide.html#mapping-generated--CreationTimestamp)
[Update Timestamp](https://docs.jboss.org/hibernate/stable/orm/userguide/html_single/Hibernate_User_Guide.html#mapping-generated-UpdateTimestamp)

> I forgot to make a new branch but luckily I didn't break anything, will be sure to do so this next week (the branch part not the break everything part).

Fingers crossed!
